# Generated by Django 5.1.1 on 2024-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='GIMG/%Y/%m/%d'),
        ),
    ]
